steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/4wings:$COMMIT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/4wings:$COMMIT_SHA',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'tag',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/4wings:$COMMIT_SHA',
        'gcr.io/world-fishing-827/github.com/globalfishingwatch/4wings:latest',
      ]
  

images:
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/4wings:$COMMIT_SHA'
  - 'gcr.io/world-fishing-827/github.com/globalfishingwatch/4wings:latest'
